version: '3'
services:

  vote:
    build: ./vote
    image: rolandop/voting_vote
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    image: rolandop/voting_result
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    image: rolandop/voting_worker
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    networks:      
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - front-tier
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
