apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
    autor: rolando
spec:
  type: NodePort
  selector:
    app: result
    autor: rolando
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
