apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
    autor: rolando
spec:
  type: NodePort
  selector:
    app: vote
    autor: rolando
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
